TravelStar/Controllers/HotelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;
using System.Text.Json.Serialization;
using TravelStar.Business.Interfaces;
using TravelStar.Entities;
using TravelStar.Model;
using TravelStar.Site.Models.Home;
using TravelStar.Site.Models.Hotel;
using TravelStar.Site.Models.Room;

namespace TravelStar.Site.Controllers
{
    public class HotelController : Controller
    {
        private readonly ICityBo _cityBo;
        private readonly IHotelBo _hotelBo;
        private readonly IRoomBo _roomBo;
        private readonly ICustomerBo _CustomerBo;
        private readonly IBookingBo _BookingBo;
        private readonly IEmailService _emailService;
        private readonly UserManager<AppUser> _userManager;
       
        public HotelController(ICityBo cityBo,
            IHotelBo hotelBo,
            IRoomBo roomBo,
            ICustomerBo customerBo,
            IBookingBo bookingBo,
            IEmailService emailService,
            UserManager<AppUser> userManager)
        {
            _cityBo = cityBo;
            _hotelBo = hotelBo;
            _roomBo = roomBo;
            _CustomerBo = customerBo;
            _BookingBo = bookingBo;
            _emailService = emailService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            return View(currentUser);
        }

        [Authorize(Roles = "Admin, SuperAdmin")]
        [HttpPost("createhotel")]
        public IActionResult CreateHotel(CreateHotelModel model)
        {
            try
            {
                using (var unitofwork = _hotelBo.NewDbContext())
                {
                    Hotel entity = new()
                    {
                        Name = model.Name,
                        Phone = model.Phone,
                        Address = model.Address,
                        WardId = model.WardId,
                        UserId = model.UserId
                    };
                    Hotel? hotelNew = _hotelBo.InsertEntity(entity, unitofwork);

                    if (hotelNew is not null)
                    {
                        foreach (var image in model.Images)
                        {
                            if (image.Length > 0)
                            {
                                //Get url To Save
                                string uploadFolderPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/hotels/" + hotelNew.Id);
                                Directory.CreateDirectory(uploadFolderPath);
                                string SavePath = Path.Combine(uploadFolderPath, image.FileName);
                                using (var stream = new FileStream(SavePath, FileMode.Create))
                                {
                                    image.CopyTo(stream);
                                }
                            }
                        }
                    }
                    return Json(true);
                }
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetHotelListAsync()
        {
            AppUser currentUser = await _userManager.GetUserAsync(HttpContext.User);
            using (var unitOfWork = _hotelBo.NewDbContext())
            {
                IQueryable<Hotel> hotelList = _hotelBo.GetEntities(unitOfWork)
                    //.Where(x => x.UserId == currentUser.Id)
                    .Include(x => x.User)
                    .Include(x => x.Ward)
                        .ThenInclude(x => x!.District)
                            .ThenInclude(x => x!.City);

                if (!User.IsInRole("SuperAdmin"))
                {
                    hotelList = hotelList.Where(x => x.UserId == currentUser.Id);
                }

                List<HotelViewModel> hotelListViewModel = new List<HotelViewModel>();
                foreach (Hotel item in hotelList)
                {
                    HotelViewModel hotelViewModel = new()
                    {
                        Id = item.Id,
                        Name = item.Name,
                        Address = item.Address,
                        Phone = item.Phone,
                        WardId = item.WardId,
                        Ward = item.Ward!.Name,
                        District = item.Ward.District!.Name,
                        City = item.Ward.District.City!.Name,
                        EmailOwner = item.User is not null ? item.User.Email : string.Empty,
                        IsSuperAdmin = User.IsInRole("SuperAdmin")
                    };

                    hotelListViewModel.Add(hotelViewModel);
                }

                return Json(new { data = hotelListViewModel });
            }
        }

        [HttpPost]
        public IActionResult SearchHotel(SearchHotelModel model)
        {
            using (var unitOfWork = _hotelBo.NewDbContext())
            {
                //Lấy Room Id đã được booking
                List<int> roomIds = _BookingBo.GetEntities(unitOfWork)
                    .Where(x => x.CancelDate == null && ((x.CheckInDate.Date <= model.CheckInDate!.Value.Date && x.CheckOutDate.Date >= model.CheckInDate!.Value.Date) ||
                    (x.CheckInDate.Date <= model.CheckOutDate!.Value.Date && x.CheckOutDate.Date >= model.CheckOutDate!.Value.Date)))
                    .Select(x => x.RoomId).ToList();

                List<Hotel> hotelList = _hotelBo.GetEntities(unitOfWork)
                    .Include(x => x.Rooms!.Where(x => !roomIds.Contains(x.Id)))
                    .Include(x => x.Ward)
                        .ThenInclude(x => x!.District)
                            .ThenInclude(x => x!.City)
                    .Where(x => x.Name!.Contains(model.City!) || x.Ward!.District!.City!.Name!.Contains(model.City!)).ToList();

                //Lấy những hotel còn room
                hotelList = hotelList.Where(x => x.Rooms!.Count() > 0).ToList();

                List<HotelViewModel> hotelListViewModel = new List<HotelViewModel>();
                foreach (Hotel item in hotelList)
                {
                    HotelViewModel hotelViewModel = new()
                    {
                        Id = item.Id,
                        Name = item.Name,
                        Address = item.Address,
                        Phone = item.Phone,
                        WardId = item.WardId,
                        Ward = item.Ward!.Name,
                        District = item.Ward.District!.Name,
                        City = item.Ward.District.City!.Name,
                        MinPrice = item.Rooms!.MinBy(x => x.Price)!.Price
                    };

                    hotelListViewModel.Add(hotelViewModel);
                }

                SearchViewModel modelSearch = new()
                {
                    HotelList = hotelListViewModel,
                };

                return PartialView("~/Views/Home/_HotelList.cshtml", modelSearch);
            }
        }

        [HttpGet("city")]
        public IActionResult GetCity()
        {
            using (var unitOfWork = _cityBo.NewDbContext())
            {
                List<City> cityList = _cityBo.GetEntities(unitOfWork).Include(x => x.Districts!).ThenInclude(x => x.Wards).ToList();

                JsonSerializerOptions options = new()
                {
                    ReferenceHandler = ReferenceHandler.IgnoreCycles,
                    WriteIndented = true
                };

                return Json(new { cityList = cityList }, options);
            }
        }

        [HttpPost("remove")]
        public IActionResult DeleteHotel(int id)
        {
            using (var unitOfWork = _hotelBo.NewDbContext())
            {
                Hotel hotelEntitty = _hotelBo.GetById(unitOfWork, id);

                try
                {
                    _hotelBo.DeleteEntity(hotelEntitty, unitOfWork);
                    return Json(true);
                }
                catch (Exception ex)
                {
                    return Json(false);
                }
            }
        }

        [HttpGet("/hotel/rooms")]
        public IActionResult GetRoomList(int hotelId, DateTime checkInDate, DateTime checkOutDate)
        {
            using (var unitOfWork = _hotelBo.NewDbContext())
            {
                List<int> roomIds = _BookingBo.GetEntities(unitOfWork)
                    .Where(x => (x.CheckInDate.Date > checkInDate.Date && x.CheckInDate.Date > checkOutDate.Date) || (x.CheckOutDate.Date > checkInDate.Date && x.CheckOutDate.Date > checkOutDate.Date))
                    .Select(x => x.RoomId).ToList();

                Hotel? hotel = _hotelBo.GetEntities(unitOfWork, x => x.Id == hotelId)
                    .Include(x => x.Rooms)
                    .Include(x => x.Ward)
                        .ThenInclude(x => x!.District)
                            .ThenInclude(x => x!.City).FirstOrDefault();

                HotelModel hotelModel = new();
                if (hotel is not null)
                {
                    hotelModel.Id = hotel.Id;
                    hotelModel.Name = hotel.Name;
                    hotelModel.Address = hotel.Address;
                    hotelModel.Phone = hotel.Phone;
                    hotelModel.WardId = hotel.WardId;
                    hotelModel.Ward = hotel.Ward!.Name;
                    hotelModel.District = hotel.Ward.District!.Name;
                    hotelModel.City = hotel.Ward.District.City!.Name;
                    hotelModel.CheckInDate = checkInDate;
                    hotelModel.CheckOutDate = checkOutDate;

TravelStar/Controllers/RevenueController.cs
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Office2013.Word;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Data;
using TravelStar.Business.Implements;
using TravelStar.Business.Interfaces;
using TravelStar.Entities;
using TravelStar.Site.Models.Hotel;
using TravelStar.Site.Models.Revenue;

namespace TravelStar.Site.Controllers
{
    public class RevenueController : Controller
    {
        private readonly IBookingBo _BookingBo;

        public RevenueController(
            IBookingBo bookingBo)
        {
            _BookingBo = bookingBo;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetBookingList(DateTime? fromDate = null!, DateTime? toDate = null!)
        {
            using (var unitOfWork = _BookingBo.NewDbContext())
            {
                IQueryable<Booking> BookingList = _BookingBo.GetEntities(unitOfWork)
                       .Include(x => x.Customer)
                       .Include(x => x.Room)
                       .ThenInclude(x => x!.Hotel)
                       .Where(x => x.PaymentDate.HasValue);

                if (fromDate is not null)
                {
                    BookingList = BookingList.Where(x => x.CheckInDate.Date >= fromDate.Value.Date);
                }

                if (toDate is not null)
                {
                    BookingList = BookingList.Where(x => x.CheckInDate.Date <= toDate.Value.Date);
                }

                List<BookingViewModel> bookingListViewModel = new List<BookingViewModel>();
                foreach (Booking item in BookingList.OrderBy(x => x.CheckInDate.Date).ToList())
                {
                    BookingViewModel bookingViewModel = new()
                    {
                        Id = item.Id,
                        CheckInDate = item.CheckInDate.Day.ToString() + "/" + item.CheckInDate.Month.ToString() + "/" + item.CheckInDate.Year.ToString(),
                        CheckOutDate = item.CheckOutDate.Day.ToString() + "/" + item.CheckOutDate.Month.ToString() + "/" + item.CheckOutDate.Year.ToString(),
                        RoomName = item.Room is not null && !string.IsNullOrEmpty(item.Room.Name) ? item.Room.Name : string.Empty,
                        CustomerEmail = item.Customer is not null && !string.IsNullOrEmpty(item.Customer.Email) ? item.Customer.Email : string.Empty,
                        TotalPrice = item.TotalPrice,
                        HotelName = item.Room!.Hotel!.Name,
                    };

                    bookingListViewModel.Add(bookingViewModel);
                }

                return Json(new { data = bookingListViewModel });
            }
        }

        [HttpGet]
        public Task<FileResult> ExportRevenueInExcel(DateTime? fromDate = null!, DateTime? toDate = null!)
        {
            using (var unitOfWork = _BookingBo.NewDbContext())
            {
                IQueryable<Booking> bookings = _BookingBo.GetEntities(unitOfWork)
                       .Include(x => x.Customer)
                       .Include(x => x.Room)
                       .ThenInclude(x => x!.Hotel)
                       .Where(x => x.PaymentDate.HasValue);


                if (fromDate is not null)
                {
                    bookings = bookings.Where(x => x.CheckInDate.Date >= fromDate.Value.Date);
                }

                if (toDate is not null)
                {
                    bookings = bookings.Where(x => x.CheckInDate.Date <= toDate.Value.Date);
                }

                string fileName = "Revenue.xlsx";
                return Task.FromResult(GenerateExcel(fileName, bookings.ToList()));
            }    
            
        }

        private FileResult GenerateExcel(string fileName, List<Booking> bookings)
        {
            DataTable dataTable = new DataTable("revenue");
            dataTable.Columns.AddRange(new DataColumn[]
            {
                new DataColumn("Id"),
                new DataColumn("CheckInDate"),
                new DataColumn("CheckOutDate"),
                new DataColumn("RoomName"),
                new DataColumn("CustomerEmail"),
                new DataColumn("ToTalPrice"),
                new DataColumn("HotelName")
            });

            foreach (Booking booking in bookings)
            {
                dataTable.Rows.Add(booking.Id,
                                   booking.CheckInDate,
                                   booking.CheckOutDate,
                                   booking.Room!.Name,
                                   booking.Customer!.Email,
                                   booking.TotalPrice,
                                   booking.Room!.Hotel!.Name);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dataTable);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);

                    return File(stream.ToArray(),
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    fileName);
                }
            }
        }
    }
}

TravelStar/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TravelStar.Site.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        public async Task<IActionResult> AddRole(string roleName)
        {
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }
            return RedirectToAction("Index");
        }
    }
}

TravelStar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TravelStar</title>
    <link rel="stylesheet" href="~/lib/sweetalert/sweetalert.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/fontawesome-free-6.1.2-web/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.12.1/af-2.4.0/b-2.2.3/b-colvis-2.2.3/b-html5-2.2.3/b-print-2.2.3/cr-1.5.6/date-1.1.2/fc-4.1.0/fh-3.2.4/kt-2.7.0/r-2.3.0/rg-1.2.0/rr-1.2.8/sc-2.0.7/sb-1.3.4/sp-2.0.2/sl-1.4.0/sr-1.1.1/datatables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />

    <link href="~/lib/template/css/elegant-icons.css" rel="stylesheet" />
    <link href="~/lib/template/css/flaticon.css" rel="stylesheet" />
    <link href="~/lib/template/css/owl.carousel.min.css" rel="stylesheet" />
    @*<link href="~/lib/template/css/nice-select.css" rel="stylesheet" />*@
    <link href="~/lib/template/css/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/lib/template/css/magnific-popup.css" rel="stylesheet" />
    <link href="~/lib/template/css/slicknav.min.css" rel="stylesheet" />
    <link href="~/lib/template/css/style.css" rel="stylesheet" />
</head>
<body>
    <header class="header-section">
        <div class="top-nav">
            <div class="menu-item">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-2">
                            <div class="navbar navbar-light">
                                <a class="navbar-brand" asp-controller="Home" asp-action="Index">TravelStar</a>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="nav-menu text-left">
                                <nav class="mainmenu">
                                    <ul>
                                        <li class="active">
                                            <a asp-controller="Home" asp-action="Index">Home</a>
                                        </li>
                                        @if (User.IsInRole("SuperAdmin") || User.IsInRole("Admin"))
                                        {
                                            <li>
                                                <a asp-controller="Hotel" asp-action="Index">Hotels</a>
                                            </li>
                                        }

                                        <li>
                                            <a asp-controller="Booking" asp-action="Index">Bookings</a>
                                        </li>

                                        @if (User.IsInRole("SuperAdmin"))
                                        {
                                            <li>
                                                <a asp-controller="Account" asp-action="Index">Accounts</a>
                                            </li>
                                          @*  <li>
                                                <a asp-controller="Roles" asp-action="Index">Roles</a>
                                            </li>*@
                                        }

                                         @if (User.IsInRole("SuperAdmin") || User.IsInRole("Admin"))
                                        {
                                            <li>
                                                <a asp-controller="Revenue" asp-action="Index">Revenues</a>
                                            </li>
                                        }
                                        @*<li><a href="./rooms.html">Rooms</a></li>
                                        <li><a href="./about-us.html">About Us</a></li>
                                        <li>
                                        <a href="./pages.html">Pages</a>
                                        <ul class="dropdown">
                                        <li><a href="./room-details.html">Room Details</a></li>
                                        <li><a href="./blog-details.html">Blog Details</a></li>
                                        <li><a href="#">Family Room</a></li>
                                        <li><a href="#">Premium Room</a></li>
                                        </ul>
                                        </li>
                                        <li><a href="./blog.html">News</a></li>*@

                                        @*<li><a asp-controller="Home" asp-action="Index">Contact</a></li>*@
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="nav-menu">
                                <nav class="mainmenu">
                                    <partial name="_LoginPartial" />
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    @*<div class="container">
        <main role="main" class="pb-3">
            
        </main>
    </div>*@

    @RenderBody()

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TravelStar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.12.1/af-2.4.0/b-2.2.3/b-colvis-2.2.3/b-html5-2.2.3/b-print-2.2.3/cr-1.5.6/date-1.1.2/fc-4.1.0/fh-3.2.4/kt-2.7.0/r-2.3.0/rg-1.2.0/rr-1.2.8/sc-2.0.7/sb-1.3.4/sp-2.0.2/sl-1.4.0/sr-1.1.1/datatables.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/lib/template/js/jquery.magnific-popup.min.js"></script>
    @*<script src="~/lib/template/js/jquery.nice-select.min.js"></script>*@
    <script src="~/lib/template/js/jquery-ui.min.js"></script>
    <script src="~/lib/template/js/jquery.slicknav.js"></script>
    <script src="~/lib/template/js/owl.carousel.min.js"></script>
    <script src="~/lib/template/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>