TravelStar/Controllers/PermissionController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TravelStar.Site.Constants;
using TravelStar.Site.Helpers;
using TravelStar.Site.Models.Permission;

namespace TravelStar.Site.Controllers
{
    public class PermissionController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public PermissionController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index(string roleId)
        {
            var model = new PermissionViewModel();
            var allPermissions = new List<RoleClaimsViewModel>();
            allPermissions.GetPermissions(typeof(Permissions.ManageHotel), roleId);

            var role = await _roleManager.FindByIdAsync(roleId);
            model.RoleId = roleId;
            var claims = await _roleManager.GetClaimsAsync(role);

            var allClaimValues = allPermissions.Select(x => x.Value).ToList();

            var roleClaimValues = claims.Select(x => x.Value).ToList();

            var authorizedClaims = allClaimValues.Intersect(roleClaimValues).ToList();

            foreach (var permission in allPermissions)
            {
                if (authorizedClaims.Any(x => x == permission.Value))
                {
                    permission.Selected = true;
                }
            }
            model.RoleClaims = allPermissions;
            return View(model);
        }

        public async Task<IActionResult> Update(PermissionViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.RoleId);
            var claims = await _roleManager.GetClaimsAsync(role);

            foreach (var claim in claims)
            {
                await _roleManager.RemoveClaimAsync(role, claim);
            }

            var selectedClaims = model.RoleClaims.Where(x => x.Selected).ToList();
            foreach (var claim in selectedClaims)
            {
                await _roleManager.AddPermissionClaim(role, claim.Value);
            }

            return RedirectToAction("Index", new { roleId = model.RoleId });
        }
    }
}

TravelStar/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TravelStar.Site.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        public async Task<IActionResult> AddRole(string roleName)
        {
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }
            return RedirectToAction("Index");
        }
    }
}

TravelStar/Views/Roles/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@model IEnumerable<IdentityRole>
<h1>Roles</h1>
<br />
<form method="post" asp-action="addrole" asp-controller="roles">
    <div class="input-group">
        <input name="roleName" class="form-control w-25" />
        @*<span class="input-group-btn">
            <button class="btn btn-info">Add New Role</button>
        </span>*@

    </div>
</form>
<table class="table table-striped" id="roleTable">
    <thead>
        <tr>
            <th>Id</th>
            <th>Role</th>
            @*<th style="width:20%"></th>*@
        </tr>
    </thead>
    <tbody>
        @foreach (var role in Model)
        {
            <tr>
                <td>
                    @role.Id
                </td>
                <td>
                    @role.Name
                </td>
                @*<td class="text-left">
                    <div class="btn-group dropleft">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Action
                        </button>
                        <div class="dropdown-menu shadow animated--grow-in">
                            <a class="dropdown-item">
                                <i class="fas fa-pencil-alt"></i>
                                Edit
                            </a>
                            <form class="d-inline">
                                <a class="dropdown-item">
                                    <i class="fas fa-trash-alt"></i>
                                    Delete
                                </a>
                            </form>
                            <a style="margin-right:16px" asp-controller="Permission" asp-action="Index" asp-route-roleId="@role.Id" class="dropdown-item">
                                <i class="fas fa-wrench"></i>
                                Manage Permisions
                            </a>
                        </div>
                    </div>
                </td>*@
            </tr>
        }
    </tbody>

</table>