TravelStar/Models/Revenue/BookingViewModel.cs
namespace TravelStar.Site.Models.Revenue
{
    public class BookingViewModel
    {
        public int Id { get; set; }
        public string? CheckInDate { get; set; }
        public string? CheckOutDate { get; set; }
        public string? RoomName { get; set; }
        public string? CustomerEmail { get; set; }
        public long TotalPrice { get; set; }
        public string? HotelName { get; set; }
        public int HotelId { get; set; }
    }
}

TravelStar/Controllers/BookingController.cs
using BraintreeHttp;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PayPal.Core;
using PayPal.v1.Payments;
using System.Net;
using TravelStar.Business.Implements;
using TravelStar.Business.Interfaces;
using TravelStar.Entities;
using TravelStar.Repositories.UnitOfWork;
using HttpResponse = BraintreeHttp.HttpResponse;

namespace TravelStar.Site.Controllers
{
    public class BookingController : Controller
    {
        private readonly IBookingBo _BookingBo;
        private readonly string _clientId;
        private readonly string _secretKey;

        public BookingController(
            IBookingBo bookingBo,
            IConfiguration config)
        {
            _BookingBo = bookingBo;
            _clientId = config["Paypal:ClientId"];
            _secretKey = config["Paypal:SecretKey"];
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("/booking/confirmcustomer")]
        public IActionResult GetBookingByEmail(string email)
        {
            using (var unitOfWork = _BookingBo.NewDbContext())
            {
                if (User.IsInRole("SuperAdmin"))
                {
                    List<Booking> allbookings = _BookingBo.GetEntities(unitOfWork)
                .Include(x => x.Customer)
                .Include(x => x.Room)
                    .ThenInclude(x => x!.Hotel)
                    .ThenInclude(x => x!.Ward)
                    .ThenInclude(x => x!.District)
                    .ThenInclude(x => x!.City).ToList();
                
                    return PartialView("~/Views/Booking/_BookingList.cshtml", allbookings);
                }
                else
                {
                    List<Booking> bookings = _BookingBo.GetEntities(unitOfWork)
                .Include(x => x.Customer)
                .Include(x => x.Room)
                    .ThenInclude(x => x!.Hotel)
                    .ThenInclude(x => x!.Ward)
                    .ThenInclude(x => x!.District)
                    .ThenInclude(x => x!.City)
                .Where(x => x.Customer!.Email!.Equals(email)).ToList();

                    return PartialView("~/Views/Booking/_BookingList.cshtml", bookings);
                }

            }
        }


        [HttpPost("cancelbooking")]
        public IActionResult CancelBooking(int id)
        {
            using (var unitOfWork = _BookingBo.NewDbContext())
            {
                Booking bookingEntitty = _BookingBo.GetById(unitOfWork, id);

                try
                {
                    bookingEntitty.CancelDate = DateTime.Now;
                    _BookingBo.UpdateEntity(bookingEntitty, id, unitOfWork);
                    return Json(true);
                }
                catch (Exception ex)
                {
                    return Json(false);
                }
            }
        }

        public async Task<IActionResult> PaypalCheckout(int bookingId)
        {
            using (var unitOfWork = _BookingBo.NewDbContext())
            {
                Booking? booking = _BookingBo.GetEntities(unitOfWork)
                    .Include(x => x.Customer).Where(x => x.Id == bookingId).FirstOrDefault();
                if (booking is null || booking.TotalPrice == 0)
                {
                    return Redirect("/Booking/CheckoutFail");
                }

                SandboxEnvironment environment = new SandboxEnvironment(_clientId, _secretKey);
                PayPalHttpClient client = new PayPalHttpClient(environment);

                #region Create Paypal Order
                ItemList itemList = new ItemList()
                {
                    Items = new List<Item>()
                };

                long total = booking.TotalPrice;

                itemList.Items.Add(new Item()
                {
                    Name = booking.Customer!.Name,
                    Currency = "USD",
                    Price = total.ToString(),
                    Quantity = "1",
                    Sku = "bookingId_" + booking.Id,
                    Tax = "0"
                });
                #endregion

                long paypalOrderId = DateTime.Now.Ticks;
                var hostname = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}";
                var payment = new Payment()
                {
                    Intent = "sale",
                    Transactions = new List<Transaction>()
                    {
                        new Transaction()
                        {
                            Amount = new Amount()
                            {
                                Total = total.ToString(),
                                Currency = "USD",
                                Details = new AmountDetails
                                {
                                    Tax = "0",
                                    Shipping = "0",
                                    Subtotal = total.ToString()
                                }
                            },
                            ItemList = itemList,
                            Description = $"Invoice #{paypalOrderId}",
                            InvoiceNumber = paypalOrderId.ToString()
                        }
                    },
                    RedirectUrls = new RedirectUrls()
                    {
                        CancelUrl = $"{hostname}/Booking/CheckoutFail",
                        ReturnUrl = $"{hostname}/Booking/CheckoutSuccess?bookingId={booking.Id}&email={booking.Customer.Email}"
                    },
                    Payer = new Payer()
                    {
                        PaymentMethod = "paypal"
                    }
                };

                PaymentCreateRequest request = new PaymentCreateRequest();
                request.RequestBody(payment);

                try
                {
                    HttpResponse response = await client.Execute(request);
                    HttpStatusCode statusCode = response.StatusCode;
                    Payment result = response.Result<Payment>();

                    var links = result.Links.GetEnumerator();
                    string paypalRedirectUrl = null!;
                    while (links.MoveNext())
                    {
                        LinkDescriptionObject lnk = links.Current;
                        if (lnk.Rel.ToLower().Trim().Equals("approval_url"))
                        {
                            //saving the payapalredirect URL to which user will be redirected for payment  
                            paypalRedirectUrl = lnk.Href;
                        }
                    }

                    return Redirect(paypalRedirectUrl);
                }
                catch (HttpException httpException)
                {
                    var statusCode = httpException.StatusCode;
                    var debugId = httpException.Headers.GetValues("PayPal-Debug-Id").FirstOrDefault();

                    //Process when Checkout with Paypal fails
                    return Redirect("/Booking/CheckoutFail");
                }
            }
        }

        public IActionResult CheckoutFail()
        {
            return View();
        }

        public IActionResult CheckoutSuccess(int bookingId, string email)
        {
            using (var unitOfWork = _BookingBo.NewDbContext())
            {
                Booking bookingEntitty = _BookingBo.GetById(unitOfWork, bookingId);

                try
                {
                    bookingEntitty.PaymentDate = DateTime.Now;
                    _BookingBo.UpdateEntity(bookingEntitty, bookingId, unitOfWork);
                }
                catch (Exception ex)
                {
                    return Redirect("/Booking/CheckoutFail");
                }
            }
            return Redirect("/Booking/Index");
        }
    }
}

TravelStar/Views/Booking/CheckoutFail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

TravelStar/Views/Booking/CheckoutSuccess.cshtml
@{
    ViewData["Title"] = "CheckoutSuccess";
}
<h1>Bạn Đã Thanh Toán Thành Công</h1>

TravelStar/Views/Booking/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using TravelStar.Entities
@model List<Booking>

@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

@{
    bool isSignIn = SignInManager.IsSignedIn(User);

    string email = isSignIn ? UserManager.GetUserName(User)! : string.Empty;
    
}

<div id="container_booking">
</div>

<partial name="_ConfirmCustomerModal" />

@section Scripts{
    <script>
        $(() => {
            if ('@isSignIn' === 'True') {
                Booking.checkCustomerConfirm('@email');
            }else{
                $('#confirm_customer_modal').modal('show');
            }
        });
    </script>


    <script src="~/js/booking/booking.js"></script>
}

TravelStar/Views/Booking/_BookingList.cshtml
@using TravelStar.Entities
@model List<Booking>

@foreach (Booking booking in Model)
{
    <div class="card room_info mb-4 mt-4" style="background-color: #c9c9c93b;">
        <div class="card-body">
            <h4>@booking.Room!.Hotel!.Name</h4>
           @* <div class="mb-3">
                <i class="fa-solid fa-star" style="color: #ffe000"></i>
                <i class="fa-solid fa-star" style="color: #ffe000"></i>
                <i class="fa-solid fa-star" style="color: #ffe000"></i>
                <i class="fa-solid fa-star" style="color: #ffe000"></i>
                <i class="fa-solid fa-star" style="color: #ffe000"></i>
            </div>*@
            <div class="row">
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body pt-0 pl-0 pr-0">
                            <img src="~/images/1/hotel11.png" class="img-fluid" alt="...">
                        </div>
                    </div>
                </div>

                <div class="col-md-8">
                    <div class="card">
                        <div class="card-body">
                            <div>
                                <i class="fas fa-bed float-left"></i>
                                @{
                                    switch (booking.Room.Type)
                                    {
                                        case 1:

                                                <h6 class="pl-4 font-weight-bold ">&nbsp;Standard</h6>
                                            break;
                                        case 2:
                                                <h6 class="pl-4 font-weight-bold ">&nbsp;Deluxe</h6>
                                            break;
                                        case 3:
                                                <h6 class="pl-4 font-weight-bold ">&nbsp;Vip</h6>
                                            break;
                                    }
                                }
                            </div>

                            <div>
                                <i class="icon_calendar float-left"></i>
                                <h6 class="font-weight-bold"> &nbsp; @booking.CheckInDate.DayOfWeek, @booking.CheckInDate.Month/@booking.CheckInDate.Day/@booking.CheckInDate.Year - @booking.CheckOutDate.DayOfWeek, @booking.CheckOutDate.Month/@booking.CheckOutDate.Day/@booking.CheckOutDate.Year</h6>
                                <h6 class="pl-4"> Check-in: 14:00 - 00:00</h6>
                                <h6 class="pl-4"> Check-out: 1:00 - 12:00</h6>

                            </div>

                            <div class="mt-2">
                                <i class="fa-solid fa-location-dot float-left"></i>
                                <h6 class="font-weight-bold"> &nbsp; Hotel Address</h6>
                                <h6 class="pl-4">@booking.Room.Hotel.Address, @booking.Room.Hotel.Ward!.Name, @booking.Room.Hotel.Ward!.District!.Name, @booking.Room.Hotel.Ward.District.City!.Name</h6>
                            </div>

                              <div class="mt-2">
                                <i class="fa fa-users float-left"></i>
                                <h6 class="font-weight-bold">&nbsp; Email booking:</h6>
                                <h6 class="pl-4">@booking.Customer!.Email</h6>
                            </div>

                            <div class="mt-2">
                                <i class="fas fa-hand-holding-usd float-left"></i>
                                <h6 class="font-weight-bold">&nbsp; Total Payment :</h6>
                                <h5 class="pl-4" style="color : orangered">&nbsp; @booking.TotalPrice USD</h5>
                            </div>
                        </div>
                    </div>

                    
                   @if (booking.PaymentDate is null) 
                   {
                        <a asp-action="PaypalCheckout" asp-route-bookingId="@booking.Id" class="btn btn-outline-success mt-2">Paypal Payment</a>
                   }
                   else
                   {
                        <button type="button" class="btn btn-outline-success mt-2" disabled>Booking Paid</button>
                   }


                    @if (booking.CancelDate is not null)
                    {
                        <button type="button" class="btn btn-outline-danger mt-2" disabled>Canceled</button>
                    }
                    else
                    {
                        <button type="button" class="btn btn-outline-info mt-2" onclick="Booking.cancelBooking(this, '@booking.Id')">Cancel Booking</button>
                    }
                </div>
            </div>
        </div>
    </div>
}

TravelStar/Views/Booking/_ConfirmCustomerModal.cshtml
<!-- Modal -->
<div class="modal fade" id="confirm_customer_modal" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="title_confirm_booking_modal">Confirm Customer</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form class="row g-3" action="@Url.Action("confirmcustomer", "Booking")" method="get" id="confirm_customer_form">
                    <div class="form-group col-md-12 text-center">
                        <label for="confirm_code">Vui lòng nhập Email đã sử dụng khi đặt phòng trước đó.</label>
                        <input type="text" class="form-control" id="confirm_email" name="email" placeholder="Enter your email">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="Booking.closeCustomerConfirm()">Cancel</button>
                <button type="submit" class="btn btn-primary" id="save_confirm_customer_btn" onclick="Booking.checkCustomerConfirm()">Continue</button>
            </div>
        </div>
    </div>
</div>